# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/config.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63onfig/config.proto\"g\n\x0fNetworkConfigV4\x12\n\n\x02ip\x18\x01 \x01(\x07\x12\x0f\n\x07netmask\x18\x02 \x01(\x07\x12\x0f\n\x07gateway\x18\x03 \x01(\x07\x12\x11\n\tbroadcast\x18\x04 \x01(\x07\x12\x13\n\x0bmac_address\x18\x05 \x01(\x06\" \n\tNTPConfig\x12\x13\n\x0bserver_ipv4\x18\x01 \x01(\x07\";\n\x14GlobalLogLevelConfig\x12#\n\x10global_log_level\x18\x01 \x01(\x0e\x32\t.LogLevel\"\x87\x01\n\x06\x43onfig\x12%\n\x0bipv4_config\x18\x01 \x01(\x0b\x32\x10.NetworkConfigV4\x12\x1e\n\nntp_config\x18\x02 \x01(\x0b\x32\n.NTPConfig\x12\x36\n\x17global_log_level_config\x18\x03 \x01(\x0b\x32\x15.GlobalLogLevelConfig*\xa0\x01\n\x08LogLevel\x12\x19\n\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n\x0fLOG_LEVEL_TRACE\x10\x01\x12\x13\n\x0fLOG_LEVEL_DEBUG\x10\x02\x12\x12\n\x0eLOG_LEVEL_INFO\x10\x03\x12\x12\n\x0eLOG_LEVEL_WARN\x10\x04\x12\x13\n\x0fLOG_LEVEL_ERROR\x10\x05\x12\x12\n\x0eLOG_LEVEL_NONE\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGLEVEL']._serialized_start=362
  _globals['_LOGLEVEL']._serialized_end=522
  _globals['_NETWORKCONFIGV4']._serialized_start=23
  _globals['_NETWORKCONFIGV4']._serialized_end=126
  _globals['_NTPCONFIG']._serialized_start=128
  _globals['_NTPCONFIG']._serialized_end=160
  _globals['_GLOBALLOGLEVELCONFIG']._serialized_start=162
  _globals['_GLOBALLOGLEVELCONFIG']._serialized_end=221
  _globals['_CONFIG']._serialized_start=224
  _globals['_CONFIG']._serialized_end=359
# @@protoc_insertion_point(module_scope)
