# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads/fft_stream.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payloads import meta_data_pb2 as payloads_dot_meta__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19payloads/fft_stream.proto\x12\x02\x62m\x1a\x18payloads/meta_data.proto\"\xb6\x02\n\tFFTStream\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\r\x12\x13\n\x0b\x66rame_count\x18\x02 \x01(\r\x12\x13\n\x0b\x64uration_ns\x18\x04 \x01(\x04\x12\x10\n\x08\x66\x66t_bins\x18\x05 \x01(\r\x12\x10\n\x08hop_size\x18\x06 \x01(\r\x12\x11\n\tstart_bin\x18\t \x01(\r\x12!\n\nfft_window\x18\x0b \x01(\x0e\x32\r.bm.FFTWindow\x12!\n\nfft_result\x18\x0c \x01(\x0e\x32\r.bm.FFTResult\x12\x1c\n\x14\x61\x63tual_frame_rate_hz\x18\r \x01(\x01\x12\x19\n\x11\x66\x66t_frame_rate_hz\x18\x0e \x01(\x01\x12\x1f\n\tmeta_data\x18\x07 \x03(\x0b\x32\x0c.bm.MetaData\x12\x12\n\nchannel_id\x18\x08 \x01(\r*i\n\tFFTWindow\x12\x16\n\x12\x46\x46T_WINDOW_UNKNOWN\x10\x00\x12\x13\n\x0f\x46\x46T_WINDOW_HANN\x10\x01\x12\x16\n\x12\x46\x46T_WINDOW_HAMMING\x10\x02\x12\x17\n\x13\x46\x46T_WINDOW_BLACKMAN\x10\x03*U\n\tFFTResult\x12\x16\n\x12\x46\x46T_RESULT_UNKNOWN\x10\x00\x12\x18\n\x14\x46\x46T_RESULT_MAGNITUDE\x10\x01\x12\x16\n\x12\x46\x46T_RESULT_COMPLEX\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payloads.fft_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FFTWINDOW']._serialized_start=372
  _globals['_FFTWINDOW']._serialized_end=477
  _globals['_FFTRESULT']._serialized_start=479
  _globals['_FFTRESULT']._serialized_end=564
  _globals['_FFTSTREAM']._serialized_start=60
  _globals['_FFTSTREAM']._serialized_end=370
# @@protoc_insertion_point(module_scope)
