# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads/frame_stream.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payloads import meta_data_pb2 as payloads_dot_meta__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpayloads/frame_stream.proto\x12\x02\x62m\x1a\x18payloads/meta_data.proto\"\x8d\x02\n\x0b\x46rameStream\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\r\x12\x13\n\x0b\x66rame_count\x18\x02 \x01(\r\x12\x1d\n\x13target_frequency_hz\x18\x03 \x01(\x01H\x00\x12\x1a\n\x10target_period_ps\x18\x04 \x01(\x04H\x00\x12\x1d\n\x13\x61\x63tual_frequency_hz\x18\x05 \x01(\x01H\x01\x12\x1a\n\x10\x61\x63tual_period_ps\x18\x06 \x01(\x04H\x01\x12\x1f\n\tmeta_data\x18\x07 \x03(\x0b\x32\x0c.bm.MetaData\x12\x12\n\nchannel_id\x18\x08 \x01(\rB\x13\n\x11target_frame_rateB\x13\n\x11\x61\x63tual_frame_rateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payloads.frame_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAMESTREAM']._serialized_start=62
  _globals['_FRAMESTREAM']._serialized_end=331
# @@protoc_insertion_point(module_scope)
