# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads/log.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12payloads/log.proto\x12\x02\x62m\"E\n\x03Log\x12\x1e\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32\x0c.bm.Encoding\x12\x1e\n\x08severity\x18\x02 \x01(\x0e\x32\x0c.bm.Severity*\x8a\x01\n\x08Severity\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05TRACE\x10\x01\x12\t\n\x05\x44\x45\x42UG\x10\x64\x12\t\n\x04INFO\x10\xc8\x01\x12\x0b\n\x06NOTICE\x10\xac\x02\x12\x0c\n\x07WARNING\x10\x90\x03\x12\n\n\x05\x45RROR\x10\xf4\x03\x12\r\n\x08\x43RITICAL\x10\xd8\x04\x12\n\n\x05\x41LERT\x10\xbc\x05\x12\x0e\n\tEMERGENCY\x10\xa0\x06*\x1d\n\x08\x45ncoding\x12\x11\n\rENCODING_UTF8\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payloads.log_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEVERITY']._serialized_start=98
  _globals['_SEVERITY']._serialized_end=236
  _globals['_ENCODING']._serialized_start=238
  _globals['_ENCODING']._serialized_end=267
  _globals['_LOG']._serialized_start=26
  _globals['_LOG']._serialized_end=95
# @@protoc_insertion_point(module_scope)
