# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/physical_units.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bshared/physical_units.proto\x12\x02\x62m*\xfd\x07\n\x08\x44\x61taUnit\x12\r\n\tUNIT_NONE\x10\x00\x12\x0e\n\nUNIT_METRE\x10\x01\x12\x11\n\rUNIT_KILOGRAM\x10\x02\x12\x0f\n\x0bUNIT_SECOND\x10\x03\x12\x0f\n\x0bUNIT_AMPERE\x10\x04\x12\x0f\n\x0bUNIT_KELVIN\x10\x05\x12\r\n\tUNIT_MOLE\x10\x06\x12\x10\n\x0cUNIT_CANDELA\x10\x07\x12\x0f\n\x0bUNIT_NEWTON\x10\x08\x12\r\n\tUNIT_VOLT\x10\t\x12\r\n\tUNIT_WATT\x10\n\x12 \n\x1cUNIT_METER_PER_SQUARE_SECOND\x10\x0b\x12\x1e\n\x1aUNIT_DEGREE_ANG_PER_SECOND\x10\x0c\x12\x0f\n\x0bUNIT_RADIAN\x10\x1e\x12\x12\n\x0eUNIT_STERADIAN\x10\x1f\x12\x0e\n\nUNIT_HERTZ\x10 \x12\x0f\n\x0bUNIT_PASCAL\x10\"\x12\x0e\n\nUNIT_JOULE\x10#\x12\x10\n\x0cUNIT_COULOMB\x10%\x12\x0e\n\nUNIT_FARAD\x10\'\x12\x0c\n\x08UNIT_OHM\x10(\x12\x10\n\x0cUNIT_SIEMENS\x10)\x12\x0e\n\nUNIT_WEBER\x10*\x12\x0e\n\nUNIT_TESLA\x10+\x12\x0e\n\nUNIT_HENRY\x10,\x12\x17\n\x13UNIT_DEGREE_CELSIUS\x10-\x12\x0e\n\nUNIT_LUMEN\x10.\x12\x0c\n\x08UNIT_LUX\x10/\x12\x12\n\x0eUNIT_BECQUEREL\x10\x30\x12\r\n\tUNIT_GRAY\x10\x31\x12\x10\n\x0cUNIT_SIEVERT\x10\x32\x12\x12\n\x0eUNIT_GRADE_ANG\x10@\x12\x13\n\x0fUNIT_DEGREE_ANG\x10\x41\x12\x13\n\x0fUNIT_MINUTE_ANG\x10\x42\x12\x13\n\x0fUNIT_SECOND_ANG\x10\x43\x12\x0e\n\nUNIT_LITRE\x10\x44\x12\x0c\n\x08UNIT_ARE\x10\x45\x12\x10\n\x0cUNIT_HECTARE\x10\x46\x12\x0f\n\x0bUNIT_MINUTE\x10G\x12\r\n\tUNIT_HOUR\x10H\x12\x0c\n\x08UNIT_DAY\x10I\x12\r\n\tUNIT_YEAR\x10J\x12\r\n\tUNIT_GRAM\x10K\x12\x0e\n\nUNIT_TONNE\x10L\x12\x0c\n\x08UNIT_BAR\x10N\x12\x0e\n\nUNIT_POISE\x10O\x12\x0f\n\x0bUNIT_STOKES\x10P\x12\x15\n\x11UNIT_ELECTRONVOLT\x10Q\x12\x19\n\x15UNIT_ATOMIC_MASS_UNIT\x10R\x12\x18\n\x14UNIT_ASTRONOMIC_UNIT\x10S\x12\x0f\n\x0bUNIT_PARSEC\x10T\x12\x15\n\x11UNIT_NEWTON_METRE\x10V\x12\x16\n\x12UNIT_SQUARE_SECOND\x10W\x12\x15\n\x11UNIT_SQUARE_METRE\x10X\x12\x15\n\x11UNIT_CUBIIC_METRE\x10Yb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared.physical_units_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAUNIT']._serialized_start=36
  _globals['_DATAUNIT']._serialized_end=1057
# @@protoc_insertion_point(module_scope)
